myapp/dice_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class DicePostForm(FlaskForm):
    link = StringField('Burn', validators=[DataRequired()])
    submit = SubmitField('Post')

myapp/dice_posts/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint, abort
from flask_login import current_user, login_required
from myapp import db 
from myapp.models import DicePost
from myapp.dice_posts.forms import DicePostForm

dice_posts = Blueprint('dice_posts', __name__)

@dice_posts.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
    form = DicePostForm()
    if form.validate_on_submit():
        dice_post = DicePost(link=form.link.data, user_id=current_user.id)
        db.session.add(dice_post)
        db.session.commit()
        flash('Dice Post Created')
        print('Dice post was created')
        return redirect(url_for('core.index'))
    return render_template('create_post.html', form=form)



@dice_posts.route('/<int:dice_post_id>')
def dice_post(dice_post_id):
    dice_post = DicePost.query.get_or_404(dice_post_id) 
    return render_template('dice_post.html', link=dice_post.link, date=dice_post.date, post=dice_post)

@dice_posts.route('/<int:dice_post_id>/update',methods=['GET','POST'])
@login_required
def update(dice_post_id):
    dice_post = DicePost.query.get_or_404(dice_post_id)

    if dice_post.author != current_user:
        abort(403)

    form = DicePostForm()

    if form.validate_on_submit():
        dice_post.link = form.link.data
        db.session.commit()
        flash('Dice Post Updated')
        return redirect(url_for('core.index'))

    elif request.method == 'GET':
        form.link.data = dice_post.link

    return render_template('create_post.html',title='Updating',form=form)

@dice_posts.route('/<int:dice_post_id>/delete',methods=['GET','POST'])
@login_required
def delete_post(dice_post_id):

    dice_post = DicePost.query.get_or_404(dice_post_id)
    if dice_post.author != current_user:
        abort(403)

    db.session.delete(dice_post)
    db.session.commit()
    flash('Dice Post Deleted')
    return redirect(url_for('core.index'))

myapp/users/views.py
from crypt import methods
from operator import methodcaller
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from myapp import db
from myapp.models import User
from myapp.users.forms import RegistrationForm, LoginForm, UpdateUserForm

users = Blueprint('users', __name__) # dont forget to register this in __init__.py 


# register
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data, password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for Registration!')
        return redirect(url_for('users.login'))
    
    return render_template('register.html', form=form)

# login
@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Log in Success!')

            next = request.args.get('next')

            if next ==None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)

# logout
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index')) #once the user has logged out we will redirect them back home


#account (update UserForm)
@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit(): 
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User account updated!!')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    return render_template('account.html', form=form)




from myapp.models import User, DicePost


@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    dice_posts = DicePost.query.filter_by(author=user).order_by(DicePost.date.desc()).paginate(page=page, per_page=5) 
    return render_template('user_dice_posts.html', dice_posts=dice_posts, user=user)

myapp/templates/account.html
{% extends "base.html" %}
{% block content %}
   
<div class="jumbotron">
    <div align="center">
        <h1>Welcome to the page for {{current_user.username}}</h1>
    </div>
</div>

<div class="container">
    <form method="POST" action="" enctype="multipart/form-data">
        <div class="form-group">
            {{form.hidden_tag()}}
        </div>
        <div class="form-group">
            {{form.username.label(class='form-group')}} 
            {{form.username(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.email.label(class='form-group')}} 
            {{form.email(class='form-control')}}
        </div>
      
        <div class="form-group">
            {{form.submit(class='btn btn-primary')}}
        </div>
       
       
    </form>
</div>
{% endblock %}

myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Londrina+Outline&display=swap"
        rel="stylesheet">
    <link id="favicon" rel="icon" type="image/png" sizes="32x32" href="{{url_for('static', filename='flame.png')}}" />
    <title>Burn Book</title>
</head>

<body>
    <ul class="nav">
        <li id="navnav" class="nav-link">
            <a href="{{url_for('core.index')}}">Home</a>
        </li>

        {% if current_user.is_authenticated %}
        <li id="navnav" class="nav-link">
            <a href="{{url_for('users.logout')}}">Log Out</a>
        </li>
        <li id="navnav" class="nav-link">
            <a href="{{url_for('users.account')}}">Account</a>
        </li>
        <li id="navnav" class="nav-link">
            <a href="{{url_for('dice_posts.create_post')}}">Create Post</a>
        </li>
        <li id="navnav" class="nav-link">
            <a href="{{url_for('users.user_posts', username=current_user.username)}}">My Burns</a>
        </li>
        {% else %}
        <li id="navnav" class="nav-link">
            <a href="{{url_for('users.login')}}">Log In</a>
        </li>
        <li id="navnav" class="nav-link">
            <a href="{{url_for('users.register')}}">Register</a>
        </li>
        {% endif %}
    </ul>

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</body>

</html>

myapp/templates/create_post.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
      <form class="form-group" method="POST">
          {{form.hidden_tag()}}

          
          <div class="form-group">
              {{form.link.label(class="form-control-label")}}
              {{form.link(class="form-control form-control-lg")}}
          </div>
        <div id="update" class="form-group">
            {{form.submit(class="btn ")}}
        </div>
      </form>
    </div>
{% endblock %}

myapp/templates/dice_post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h2>Owned by: {{post.author.username}}</h2>
  <h3>Published: {{ post.date.strftime('%B %d, %Y') }}</h3>
  <!-- <img src="{{post.link}}" alt="dice"> -->
  <img src="{{url_for(post.link)}}">
  {% if post.author == current_user %}
    <div>
      <a class="btn btn-secondary" href="{{ url_for('dice_posts.update', dice_post_id=post.id) }}">Update</a>
      <br>
      <form action="{{ url_for('dice_posts.delete_post', dice_post_id=post.id) }}" method="POST">
        <input class="btn btn-danger" type="submit" value="Delete">
      </form>
    </div>
  {% endif %}
</div>
{% endblock content %}

myapp/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <img style="width: 18rem" src="{{url_for('static', filename='Daco.png')}}">
</div>
<div id="burns" class="container d-flex justify-content-around">
    <divc class="row ">
        {% for post in dice_posts.items %}
        <div id="burn" class="card">
            <div class="card-body">
                <h2 id="burnBody" class="card-title" href="{{url_for('dice_posts.dice_post', dice_post_id=post.id)}}">{{post.link}}
                </h2>
                {% if post.author == current_user %}
                <div id="cardBtns"  class="card-body">
                    <a id="update" class="btn btn-secondary"
                        href="{{ url_for('dice_posts.update', dice_post_id=post.id) }}">Update</a>
                    <form action="{{ url_for('dice_posts.delete_post', dice_post_id=post.id) }}" method="POST">
                        <input id="delete" class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}
</div>
</div>

<nav aria-label="Page Navigation example">
    <ul class="pagination justify-content-center">
        {% for page_num in dice_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if dice_posts.page == page_num %}
        <li class="page-item disabled">
            <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{ page_num }}</a>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
</nav>
{% endblock %}

myapp/templates/info.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1>Info about our party!!</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit veniam nihil nostrum excepturi nulla error quaerat reprehenderit, iste ad accusamus amet nesciunt, provident laborum, voluptas molestias unde non est perferendis?</p>
    </div>
   
{% endblock %}

myapp/templates/login.html
{% extends "base.html" %}
{% block content %}
   
<form method="POST">
    {{form.hidden_tag()}}
    {{form.email.label}}{{form.email}}<br>
    {{form.password.label}}{{form.password}}<br>
    {{form.submit()}}

</form>
{% endblock %}

myapp/templates/register.html
{% extends "base.html" %}
{% block content %}
   
<form method="POST">
    {{form.hidden_tag()}}
    {{form.email.label}}{{form.email}}<br>
    {{form.username.label}}{{form.username}}<br>
    {{form.password.label}}{{form.password}}<br>
    {{form.pass_confirm.label}}{{form.pass_confirm}}<br>
    {{form.submit()}}
</form>
{% endblock %}

myapp/templates/user_dice_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <div align="center">
            <h1>Welcome to the page for {{user.username}}</h1>
        </div>
    </div>
    <div id="burns" class="container">
        <divc class="row ">
            {% for post in dice_posts.items %}
            <div id="burn" class="card">
                <div class="card-body">
                    <h2 class="card-title" href="{{url_for('dice_posts.dice_post', dice_post_id=post.id)}}">
                        {{post.link}}
                    </h2>
                    {% if post.author == current_user %}
                    <div id="cardBtns">
                        <a id="update" class="btn btn-secondary"
                            href="{{ url_for('dice_posts.update', dice_post_id=post.id) }}">Update</a>
                        <form action="{{ url_for('dice_posts.delete_post', dice_post_id=post.id) }}" method="POST">
                            <input id="delete" class="btn btn-danger" type="submit" value="Delete">
                        </form>
                    </div>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
    </div>
</div>

<nav aria-label="Page Navigation example">
    <ul class="pagination justify-content-center">

        {% for page_num in dice_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if dice_posts.page == page_num %}
        <li class="page-item disabled">
            <a class="page-link" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{
                page_num }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{
                page_num }}</a>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
</nav>


{% endblock %}